version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: olehboreiko/docker-play:wordpress
     volumes:
       - wp_files:/var/www/html
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306

   db:
     image: olehboreiko/docker-play:mysql
     volumes:
       - db_files:/var/lib/mysql
     restart: always
volumes:
    wp_files:
    db_files:
